import { Rubik, Geist_Mono } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-Rubik",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export default function RootLayout({children}) {
  return (
   <html lang="en">
   <body className={"antialiased"}>
          {children}
   </body>

   </html>
  );
}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


